HOST: https://beta.mysquar.com

--- API v1 ---

GET /post-detailed
< 200
< Content-Type: application/json
{
    "id": "6ee1a1b9-ed6b-4bed-b3ea-0f13f16f3d12",
    "text": "",
    "created_at": "2014-03-24T00:02:02Z",
    "updated_at": "2014-03-24T00:04:00Z",
    "replies": [
        {
            "id": "9e36fc72-76c3-4aa3-89e5-39a70c9f1090",
            "text": "ဟုတ္",
            "updated_at": "2014-03-24T00:02:53Z",
            "in_reply_to": {
                "post": { # post.api_brief_info
                    "id": "6ee1a1b9-ed6b-4bed-b3ea-0f13f16f3d12",
                    "text": "",
                    "created_at": "2014-03-24T00:02:02Z",
                    "updated_at": "2014-03-24T00:04:00Z",
                    "truncated": null,
                    "type": "post",
                    "from": {
                        "id": "54425908-fb70-4e1a-82f6-48ddec58f446",
                        "name": "lapway",
                        "username": "mghtay",
                        "avatar": "http://cdn-internal.mysquar.com/photos/5f42cb16-3ada-4ec5-b790-3fae032d1e12",
                        "badges": []
                    },
                    "in": {
                        "id": 1390350200,
                        "uuid": "5824eac0-56ee-4de0-843b-977d51bcf5f4",
                        "title": "စကားေျပာေနေသာပံုရိပ္မ်ား",
                        "flag_id": null,
                        "preserved": false
                    },
                    "number_of_comments": 2,
                    "number_of_likes": 2,
                    "photo": "http://cdn-internal.mysquar.com/photos/26c498c3-9f44-4a53-b572-8cce9974094b",
                    "in_reply_to": {}
                }
            },
            "from": { # user.api_brief_info
                "id": "167047b9-2cf8-4059-94e8-1af380e80ba8",
                "name": "min oo",
                "username": "doctorno18",
                "avatar": "http://cdn-internal.mysquar.com/assets/1/images/default-avatar",
                "badges": []
            },
            "type": "comment",
            "flag_id": null
        },
        Reply[]
    ],
    "from": { # user.api_brief_info
        "id": "54425908-fb70-4e1a-82f6-48ddec58f446",
        "name": "lapway",
        "username": "mghtay",
        "avatar": "http://cdn-internal.mysquar.com/photos/5f42cb16-3ada-4ec5-b790-3fae032d1e12",
        "badges": []
    },
    "in": { # topic.api_brief_info
        "id": 1390350200,
        "uuid": "5824eac0-56ee-4de0-843b-977d51bcf5f4",
        "title": "စကားေျပာေနေသာပံုရိပ္မ်ား",
        "flag_id": null,
        "preserved": false
    },
    "number_of_comments": 2,
    "number_of_likes": 2,
    "photo": "http://cdn-internal.mysquar.com/photos/26c498c3-9f44-4a53-b572-8cce9974094b",
    "like_id": null,
    "flag_id": null,
    "poll": null,
    "newbie_event": false
}


GET /post-list
< 200
< Content-Type: application/json
{
    "objects": [
        {
            "id": "2a4a9fce-bbc0-4c46-ac46-30e6cb173b77",
            "text": "fgf",
            "created_at": "2014-03-22T11:12:39Z",
            "updated_at": "2014-03-22T11:12:39Z",
            "truncated": null,
            "from": { # user.api_brief_info
                "id": "ab53d185-1b84-404c-a16d-4baf74b6c713",
                "name": "Black Hell",
                "username": "black.hell.14",
                "avatar": "http://cdn-internal.mysquar.com/photos/f105a861-b641-4447-b10b-f71560cb15d9",
                "badges": []
            },
            "in": { # topic.api_brief_info
                "id": 18,
                "uuid": "74e6138b-316a-46d7-a08a-3b55fd73923e",
                "title": "နည္းပညာ | Technology",
                "flag_id": null,
                "preserved": false
            },
            "number_of_comments": 0,
            "number_of_likes": 1,
            "type": "post",
            "photo": null,
            "like_id": null,
            "flag_id": null,
            "poll": null,
            "newbie_event": false
        },
        Post[]
    ],
    "since": "2014-04-03T10:02:51Z",
    "pagination": {
        "per_page": 2,
        "page": 1,
        "total_pages": 744,
        "total_count": 1488
    }
}


GET /notifications
< 200
< Content-Type: application/json
{
    "objects": [
        {
            "id": "ad2f1f9f-e6d4-4d5a-b819-31d869fd3294",
            "status": 1,
            "created_at": "2014-03-24T01:17:20Z",
            "type": "comment",
            "from": { # user.api_brief_info
                "id": "167047b9-2cf8-4059-94e8-1af380e80ba8",
                "username": "doctorno18",
                "email": "doctorno18@gmail.com",
                "phone": "09250700599",
                "avatar": "http://cdn-internal.mysquar.com/assets/1/images/default-avatar",
                "badges": [],
                "name": "doctorno18"
            },
            "about": {
                "comment": {
                    "id": "1abe3d2f-e441-456e-a8eb-5abafd10a69b",
                    "text": "ပံုထပ္တင္ေလ",
                    "in_reply_to": {
                        "post": {
                            "id": "94866af8-fc6a-441b-a041-320d889c808a",
                            "text": "ျပံဳးေနျပီ ေနာ္"
                        }
                    }
                }
            }
        },
        Notification[]
    ],
    "pagination": {
        "per_page": 2,
        "page": 1,
        "total_pages": 297,
        "total_count": 593
    }
}


GET /friends
< 200
< Content-Type: application/json
{
    "friends": [
        { # user.api_brief_info
            "id": "b52b98c3-e264-429d-a0a4-12aa16ee331d",
            "username": "တစ္ေယာက္ထဲခ်က္",
            "email": "7770@gmail.com",
            "phone": "33015020",
            "avatar": "http://cdn-internal.mysquar.com/assets/1/images/default-avatar",
            "badges": [],
            "name": "တစ္ေယာက္ထဲခ်က္"
        },
        Friend[]
    ]
}

GET /pending_friends
< 200
< Content-Type: application/json
{
    "friends": [
        { # user.api_friendship_info
            "id": "86578975-7429-471e-929e-f4d5107cca61",
            "username": "အာ႐ုဏ္",
            "email": "jackheart854@gmail.com",
            "phone": null,
            "avatar": "http://cdn-internal.mysquar.com/photos/e508e464-bac5-494b-bba7-56d8b8690496",
            "badges": [],
            "name": "အာ႐ုဏ္",
            "friendship": { # friendship.api_info
                "id": "169afa34-f919-48e2-970e-3d6d45895b64",
                "inviting_user_id": "86578975-7429-471e-929e-f4d5107cca61",
                "invited_user_id": "5fb31d3e-3595-4f5c-888e-ec53ca267136",
                "status": "accepted"
            }
        },
        Friend[]
    ]    
}


GET /topics-details
< 200
< Content-Type: application/json
{
    "title": "နည္းပညာ | Technology",
    "description": "",
    "created_at": "2013-05-22T07:11:17Z",
    "updated_at": "2013-10-23T08:57:57Z",
    "number_of_users": 0,
    "photo": "http://cdn-internal.mysquar.com/photos/137ee73e-e434-4f5c-90e0-806e1b75f631",
    "owner": {
        "id": "5246b81d-3fcb-4984-a180-956030a85625",
        "username": "squar",
        "email": "info@mysquar.com",
        "phone": "",
        "avatar": "http://cdn-internal.mysquar.com/photos/6d266ac7-6309-4fdb-bd44-1f73a8f3caf4",
        "badges": [
            {
                "id": "77f3c734-be5a-472e-83fa-57d9a7b9ea30",
                "title": "SQUAR အဖြဲ႕သားမ်ား",
                "url": "http://cdn-internal.mysquar.com/assets/1/images/badges/squar/{size}.png",
                "slug": "squar"
            }
        ],
        "name": "squar"
    },
    "title_my": "",
    "uuid": "74e6138b-316a-46d7-a08a-3b55fd73923e",
    "category": {
        "id": "5b35d431-98a3-4746-9e23-44b197521ab8",
        "title": "နည္းပညာ",
        "description": null
    },
    "preserved": false,
    "id": 18,
    "following": false,
    "flag_id": null,
    "number_of_followers": 2102,
    "number_of_posts": 1488
}

GET /topics-brief
< 200
< Content-Type: application/json
{ # topic.api_brief_info
    "id": 18,
    "uuid": "74e6138b-316a-46d7-a08a-3b55fd73923e",
    "title": "နည္းပညာ | Technology",
    "flag_id": null,
    "preserved": false
}

GET /categories
< 200
< Content-Type: application/json
{
    "objects": [
        {
            "id": "e6ecfc78-818c-42df-b2d8-d50783529577",
            "title": "တိရစာၦန္ကမာၻ",
            "description": null
        },
        Category[]
    ]
}
